# Input variables here

WC:
  apiKey: #ck_##################
  apiSecret: #cs_##################
  appName: #AppName
  userID: #id
  baseURL: #https://website.com
  returnURL: #https://website.com/return
  callbackURL: #https://website.com/callback
  wcVersion: #wc/v3
  endpoints:
    product: /wp-json/wc/v3/products/
    auth: /wc-auth/v1/authorize
    orders: /wp-json/wc/v3/orders
    categories: /wp-json/wc/v3/products/categories
    variations: /variations/

DBC:
  server: 'DatabaseServer'
  DB: 'Database'
  ReadUser: 'DB Read User'
  PW: 'Read User Password'
  ReadTable: '[Database].[Schema].[Table/View]'
  ReadQuery: 'SELECT [Column1], [Column2], [Column3] FROM '
  ReadWhereStmt: ' WHERE Statement'
  ReadOrderByStmt: ' ORDER BY Column DESC'

ETL:
  # FilterPrice - keys to be removed in price update automation.
  FilterPrice: ['slug', 'permalink', 'date_created', 'date_created_gmt', 'date_modified', 'date_modified_gmt', 'type', 'featured', 'catalog_visibility', 'description', 'short_description', 'regular_price', 'sale_price', 'date_on_sale_from', 'date_on_sale_from_gmt', 'date_on_sale_to', 'date_on_sale_to_gmt', 'on_sale', 'purchasable', 'total_sales', 'virtual', 'downloadable', 'downloads', 'download_limit', 'download_expiry', 'external_url', 'button_text', 'tax_status', 'tax_class', 'manage_stock', 'stock_quantity', 'backordered', 'backorders', 'backorders_allowed', 'sold_individually', 'weight', 'dimensions', 'shipping_required', 'shipping_taxable', 'shipping_class', 'shipping_class_id', 'reviews_allowed', 'average_rating', 'rating_count', 'upsell_ids', 'cross_sell_ids', 'purchase_note', 'categories', 'tags', 'images', 'attributes', 'default_attributes', 'variations', 'grouped_products', 'menu_order', 'price_html', 'related_ids']

